### ISSUE TITLE
Error for: python waf configure

### ISSUE THREAD

**Issue by ttrkaya** [jhasse/poly2tri#9]
As the readme file suggests, on my windows 10, powershell, when I type:
`python waf configure`

I get:
```
python waf configure
  set_options
Traceback (most recent call last):
  File "C:\Users\tarik\Desktop\poly2tri\waf3-1.8.20-c859ca7dc3693011756f4edf45c36626\waflib\Node.py", line 312, in ant_iter
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tarik\Desktop\poly2tri\waf3-1.8.20-c859ca7dc3693011756f4edf45c36626\waflib\Scripting.py", line 114, in waf_entry_point
    run_commands()
  File "C:\Users\tarik\Desktop\poly2tri\waf3-1.8.20-c859ca7dc3693011756f4edf45c36626\waflib\Scripting.py", line 171, in run_commands
    parse_options()
  File "C:\Users\tarik\Desktop\poly2tri\waf3-1.8.20-c859ca7dc3693011756f4edf45c36626\waflib\Scripting.py", line 144, in parse_options
    Context.create_context('options').execute()
  File "C:\Users\tarik\Desktop\poly2tri\waf3-1.8.20-c859ca7dc3693011756f4edf45c36626\waflib\Options.py", line 146, in execute
    super(OptionsContext,self).execute()
  File "C:\Users\tarik\Desktop\poly2tri\waf3-1.8.20-c859ca7dc3693011756f4edf45c36626\waflib\Context.py", line 93, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "C:\Users\tarik\Desktop\poly2tri\waf3-1.8.20-c859ca7dc3693011756f4edf45c36626\waflib\Context.py", line 134, in recurse
    user_function(self)
  File "C:\Users\tarik\Desktop\poly2tri\wscript", line 33, in options
    opt.load('compiler_cxx')
  File "C:\Users\tarik\Desktop\poly2tri\waf3-1.8.20-c859ca7dc3693011756f4edf45c36626\waflib\Context.py", line 90, in load
    fun(self)
  File "C:\Users\tarik\Desktop\poly2tri\waf3-1.8.20-c859ca7dc3693011756f4edf45c36626\waflib\Tools\compiler_cxx.py", line 36, in options
    opt.load_special_tools('cxx_*.py')
  File "C:\Users\tarik\Desktop\poly2tri\waf3-1.8.20-c859ca7dc3693011756f4edf45c36626\waflib\Context.py", line 321, in load_special_tools
    lst=self.root.find_node(waf_dir).find_node('waflib/extras').ant_glob(var)
  File "C:\Users\tarik\Desktop\poly2tri\waf3-1.8.20-c859ca7dc3693011756f4edf45c36626\waflib\Node.py", line 361, in ant_glob
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
  File "C:\Users\tarik\Desktop\poly2tri\waf3-1.8.20-c859ca7dc3693011756f4edf45c36626\waflib\Node.py", line 361, in <listcomp>
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
RuntimeError: generator raised StopIteration
```

The same thing happens on windows command line, and git bash.

**Comment by jhasse** [comment]
This is a Waf bug with newer Python versions. I've updated waf, please give it another try :)
